DXgovernance/DAVI

.github/workflows/preview-build.yml, .github/workflows/preview-deploy.yml
This PR introduces the necessary changes to get preview deployments working on the new repo.
Tested partially [here](https://github.com/mprasanjith/DAVI/pull/2). Will follow-up with a PR that should trigger the workflows so we can verify that everything works.
=> feat: Update deployment URLs.

.github/CONTRIBUTING.md, Dockerfile, package.json
Just some minor changes. Primarily to get the code deployment pipelines running and to test IPFS setup.
Just some minor changes. Primarily to get the code deployed to test IPFS deployment setup.
=> feat: Update git URLs.

.github/workflows/preview-deploy.yml, README.md
I missed to change the domain name from dxvote.dev to project-davi.dev in #34. This fixes that.
=> feat: Fix develop / production deploy URLs.

.storybook/preview.js
=> fix storybook preview

src/Components/ActionsBuilder/Action/Action.tsx, src/Components/ActionsModal/ActionsModal.tsx, src/Components/ActionsModal/components/ApproveSpendTokens/ApproveSpendTokens.tsx, src/Components/ActionsModal/components/ParamsForm/ParamsForm.tsx, src/Components/ActionsModal/types.ts
This PR implements functionality to edit actions in the action builder.
Closes #19.
What doesn't work right now:
The duration picker does not show the existing values when editing. The form renderer in the actions builder expects form components to be controlled. The current duration picker implementation is an uncontrolled component. I will be refactoring it a bit in the next PR so we can get it to work.
=> feat: Implement action builder edit functionality.

hardhat.config.js, scripts/dev.ts, scripts/updateDeployedBytecodes.js, src/bytecodes/config.json
Fix DAVI localhost build after SC changes (mainly enforcedbinaryguild removal)
=> Fix local build

package.json, scripts/dev.ts, scripts/utils/index.js, src/Components/Filter/Filter.test.tsx, src/Components/Filter/Filter.tsx, src/Components/Filter/__snapshots__/Filter.test.tsx.snap, src/Components/Filter/components/FilterMenu/FilterMenu.tsx, src/Modules/Guilds/Wrappers/ProposalCardWrapper.tsx, src/Modules/Guilds/pages/Guilds.tsx, src/bytecodes/config.json, src/contexts/Guilds/filters.tsx, src/hooks/Guilds/guild/useProposalCalls.ts, src/hooks/Guilds/useMenu.ts, yarn.lock
- Add search proposal feature
- Add filter proposal by state feature
- Add filter proposal by action type feature
- Add filter proposal by token feature
- Add dev script utility
Closes https://github.com/DXgovernance/DAVI/issues/23
Closes https://github.com/DXgovernance/DAVI/issues/24
=> Enable search and filter by proposal state

src/hooks/Guilds/contracts/useRichContractRegistry.ts
Adds working generic calls in localhost dev environment using runtime created vesting and nft contracts.
Closes #26 
=> feat: Adding usable generic calls to localhost

src/Components/Filter/Filter.tsx, src/Components/GuildCard/GuildCard.tsx, src/Components/GuildCard/__snapshots__/GuildCard.test.tsx.snap, src/Components/StakeTokensModal/components/StakeTokensButton/StakeTokenButton.tsx, src/utils/helpers.ts
Closes #64 
Manual testing. All previous tests passed.
=> Fixed extra slash in url while navigating in certain conditions

src/Components/ActionsBuilder/SupportedActions/ERC20Transfer/ERC20TransferEditor.test.tsx, src/Components/ActionsBuilder/SupportedActions/ERC20Transfer/ERC20TransferEditor.tsx, src/Components/ActionsBuilder/SupportedActions/ERC20Transfer/__snapshots__/ERC20TransferEditor.test.tsx.snap, src/Components/ActionsBuilder/SupportedActions/ERC20Transfer/validateERC20Transfer.ts, src/Components/ActionsBuilder/SupportedActions/index.tsx, src/Components/ActionsModal/ActionsModal.tsx, src/Components/ActionsModal/__snapshots__/ActionsModal.test.tsx.snap, src/Components/Primitives/Forms/Control.tsx, src/Components/ProposalCard/__snapshots__/ProposalCard.test.tsx.snap, src/Components/ProposalCard/__snapshots__/ProposalCardActionSummary.test.tsx.snap, src/bytecodes/config.json, src/locales/en/translation.json
Validate ActionBuilder - erc20transfer action
Closes https://github.com/DXgovernance/DAVI/issues/131
=> Validate ERC20Transfer Editor - ActionBuilder

src/Modules/Guilds/pages/CreateProposal.tsx
Referes to this issue: https://github.com/DXgovernance/DAVI/issues/144
Removed the reference link since we will soon have forum features built in.
Manually.
=> feat: removed reference link

package.json, src/Modules/Guilds/pages/Guilds.tsx, yarn.lock
Added `react-virtuoso` library ([link](https://virtuoso.dev/)) to handle a high number of proposals.
It uses infinite scrolling to show proposals in batches, loading 10 more when the end is reached.
It currently causes some lag due to the number of renderings caused by `useEtherSWR` that should be addressed in a future issue
Closes #130
Manual testing.
=> Handle a big number of proposals

src/Components/ProposalVoteCard/ProposalVoteCard.tsx
'Against' option showing as '0' in proposal vote modal
Closes #152 
=> Fix: 'Against' option showing as '0' in proposal vote modal

src/Components/Primitives/Forms/DurationInput/DurationInput.test.tsx, src/hooks/Guilds/useDuration/index.ts
When clicking multiple times to increase a duration time period, the values were incorrectly added.
Closes #135
=> Fix: Duration double click bug

src/Components/ActionsBuilder/SupportedActions/GenericCall/GenericCallInfoLine.tsx, src/hooks/Guilds/guild/useProposalCalls.ts, src/hooks/Guilds/useExecutable/index.ts
Bug was causing the UI to crash when trying to create a DXD vesting contract.
Issue: https://github.com/DXgovernance/DAVI/issues/143
Manually.
=> fix: made it possible to create DXD vesting contract

src/Modules/Guilds/pages/Guilds.tsx
When creating a proposal, if the number of proposals was low, an infinite loop error caused the page to crash.
Closes #179 
Manual testing.
=> Fix: white page after creating a proposal

src/Components/ActionsBuilder/CallDetails/CallDetails.tsx, src/Components/ActionsBuilder/CallDetails/__snapshots__/CallDetails.test.tsx.snap, src/Components/ActionsBuilder/types.ts, src/hooks/Guilds/guild/useProposalCalls.ts
Fix issue with approval calls
Closes https://github.com/DXgovernance/DAVI/issues/173
=> Fix approval actions

src/configs/goerli/config.json
New deployment of goerli 
`Contracts deployed: {
fromBlock: 7391375,
avatar: null,
reputation: null,
token: null,
controller: null,
permissionRegistry: null,
schemes: {},
utils: {},
votingMachines: {},
addresses: {
SWPR: '0xF56183c0276205C3fe50300dea387ac05d5e0E31',
MREP: '0xf3244AeBC12ad1a3b403c1b6382f057F1Eb88f65',
PermissionRegistry: '0x42845C3776Eb0c740EA96d5d0B3f6A21f47deF35',
GuildRegistry: '0x8acC252139e879F726B743E447dA01359F3a627f',
SWPRGuild: '0xd717be9BAfAFc9DAE0eB2a8D1986b00BC5707D72',
'SWPRGuild-vault': '0x0E4bAb07a7B2752832315C7C60386d0D76528524',
'Multisig #1': '0xba97F6ff8B6DbED26a1d0f82218dFcD6D9de5708',
'Multisig #1-vault': '0x4A4DFD6168BCDA68c4F92A6F534B666384683Bb0'
},
guildRegistry: '0x8acC252139e879F726B743E447dA01359F3a627f'
}`
Please describe the …
=> feat: New deployment addresses

src/Components/ActionsBuilder/SupportedActions/index.tsx
This correctly sets permissions with a new fromTime
=> fix: Use boolean value and rename to allowed when setting permissions

src/Components/ActionsBuilder/CallDetails/CallDetails.tsx, src/hooks/Guilds/contracts/useEncodedCall.ts, src/hooks/Guilds/guild/useProposalCalls.ts
Fix approval call fields when encoding and decoding 
Closes https://github.com/DXgovernance/DAVI/issues/197
Closes #221 
=> Fix encode & decode values for approval calls

src/Components/ProposalVoteCard/ProposalVoteCard.tsx, src/Components/ProposalVoteCard/components/VoteConfirmationModal/VoteConfirmationModal.tsx, src/Components/ProposalVoteCard/types.ts, src/Modules/Guilds/Wrappers/ProposalVoteCardWrapper.tsx
We just had quorum as the current vote amount before. Now we take the current vote amount for the selected action and add the user's power to that.
We also need #226 to prevent this logic from just showing additional votes going over 100%
Closes #225
=> fix: Fix vote impact logic

src/Modules/Guilds/pages/Governance/Governance.tsx, src/components/GuildSidebar/GuildSidebar.tsx, src/components/GuildSidebar/__snapshots__/GuildSidebar.test.tsx.snap
=> fix: Adding missed changes to all-proposals url

src/Modules/Guilds/pages/LandingPage/LandingPage.tsx
Small bug where we had colons appearing in between our loading cards
=> fix: Removing semi colons from jsx

src/Modules/Guilds/Wrappers/ProposalCardWrapper.tsx, src/Modules/Guilds/pages/Governance/Governance.tsx, src/contexts/Guilds/filters.tsx, src/hooks/Guilds/useMenu.ts
Fix ProposalCardWrapper filters and improve filter hook types. 
Closes https://github.com/DXgovernance/DAVI/issues/205
=> Fix proposals filter

src/components/ActionsBuilder/Action/Action.tsx, src/components/ActionsBuilder/CallDetails/CallDetails.test.tsx, src/components/ActionsBuilder/CallDetails/CallDetails.tsx, src/components/ActionsBuilder/CallDetails/__snapshots__/CallDetails.test.tsx.snap, src/components/ActionsBuilder/CallDetails/fixtures.ts, src/components/ActionsBuilder/SupportedActions/GenericCall/fixtures.ts, src/components/ActionsBuilder/UndecodableCalls/fixtures.ts, src/components/ActionsBuilder/types.ts, src/components/ActionsModal/ActionsModal.tsx, src/components/ActionsModal/components/ApproveSpendTokens/ApproveSpendTokens.tsx, src/hooks/Guilds/guild/useProposalCalls.ts
Closes https://github.com/DXgovernance/DAVI/issues/196
=> Add summary for spending calls

src/Modules/Guilds/pages/CreateProposal.tsx, src/hooks/Guilds/guild/useProposalCalls.ts
Fix useProposalCalls to display correct calls in ActionsBuilder options
Proposal calls are being shown under the wrong option. 
I added call details on the proposal description to be sure of how I submitted the proposal
=> Fix useProposalCalls

scripts/dev.ts
Allow Swpr guild to transfer swpr token.
Closes https://github.com/DXgovernance/DAVI/issues/166
=> Add SWPR token transfer permissions on localhost for swapr guild

src/Modules/Guilds/pages/CreateProposal.tsx
Allows the creation of signal proposals: proposals with options and no actions.
You can vote on them, but trying to execute them causes a `Failed` state.
Closes #264 
=> feat: allow for signal proposals

src/bytecodes/local.json, src/components/GuildSidebar/GuildSidebar.styled.tsx, src/components/GuildSidebar/GuildSidebar.tsx, src/components/GuildSidebar/__snapshots__/GuildSidebar.test.tsx.snap
Added member icon to the upper left.
NOTE: The information button was deliberately left out of this PR as per the comments in the issue.
Closes # [(issue)](https://github.com/DXgovernance/DAVI/issues/93)
React testing library snapshot.
=> Missing icons and buttons

cypress/integration/Guilds/Guilds.spec.ts, src/Modules/Guilds/Hooks/types.ts, src/Modules/Guilds/Hooks/useCurrentSnapshotId.ts, src/Modules/Guilds/Hooks/useProposal.ts, src/Modules/Guilds/Hooks/useProposalVotesOfVoter.ts, src/Modules/Guilds/Hooks/useTotalLocked.ts, src/Modules/Guilds/Wrappers/ProposalVoteCardWrapper.tsx, src/components/ProposalVoteCard/ProposalVoteCard.styled.ts, src/components/ProposalVoteCard/ProposalVoteCard.tsx, src/components/ProposalVoteCard/__snapshots__/ProposalVoteCard.test.tsx.snap, src/components/ProposalVoteCard/components/UserVote/UserVote.styled.ts, src/components/ProposalVoteCard/components/UserVote/UserVote.tsx, src/components/ProposalVoteCard/components/UserVote/index.ts, src/components/ProposalVoteCard/components/UserVote/types.ts, src/components/ProposalVoteCard/components/VoteChart/VoteChart.tsx, src/components/ProposalVoteCard/components/VoteChart/__snapshots__/VoteChart.test.tsx.snap, src/components/ProposalVoteCard/components/VoteResults/VoteResults.tsx, src/components/ProposalVoteCard/components/VoteResults/__snapshots__/VoteResults.test.tsx.snap, src/components/ProposalVoteCard/fixture.ts, src/components/ProposalVoteCard/types.ts, src/locales/en/translation.json
Once user has voted we hide voting options and show current voting info (option, voting power)
Closes https://github.com/DXgovernance/DAVI/issues/226
https://user-images.githubusercontent.com/25844967/189226245-f024908c-530a-41b6-b649-0146cf1e604f.mov
=> Display voted option

README.md
We still had dxvote readme in here, just updating things a bit.
Let me know if there is anything I missed :)
=> docs: Added davi readme

package.json
=> docs: Incrementing version

src/hooks/Guilds/ens/useENSPublicResolverContract.ts
=> Remove debugger from useEnsResolver hook

src/components/Web3Modals/SyncRouterWithWagmi/index.tsx
Fixes issues with app not properly reconnecting to the previously connected wallet and chain when opening a page in a new tab.
Closes #336.
=> fix: Reconnect to the last chain and wallet correctly.

hardhat.config.js
This PR changes the block time for local hardhat node to reduce the number of requests wagmi makes in watch mode.
=> fix: Change block time for local hardhat node.

src/Modules/Guilds/pages/AllProposals/AllProposals.styled.tsx
=> Hotfix: fixed vertical scrollbar in all proposals page

richContracts.json, src/configs/index.ts
This lets us vote in a super simple way with DXD guild on DXdao proposals. Will be improved by #297 and even more from future planned features that mirror proposals automatically. 
=> feat: Adding new contract to vote on dxdao in rich contracts

package.json, src/Modules/Guilds/pages/CreateDiscussion.tsx, yarn.lock
Fixed bug preventing a user to create a new discussion.
Closes #375 
Manual testing.
=> Fix: bug preventing discussion creation

src/provider/providers.ts, src/utils/constants.ts
=> fix: Updating alchemy key

src/bytecodes/prod.json
=> fix: Updating bytecodes

src/bytecodes/prod.json
=> Feature/update bytecodes 2.0

src/bytecodes/prod.json
=> fix: Updating bytecode for snapshot erc20 guild

src/App.tsx, src/components/OnlineStatus/OnlineStatus.styled.tsx, src/components/OnlineStatus/OnlineStatus.test.tsx, src/components/OnlineStatus/OnlineStatus.tsx, src/components/OnlineStatus/__snapshots__/OnlineStatus.test.tsx.snap, src/components/OnlineStatus/index.ts, src/hooks/Guilds/useOnlineStatus.ts, src/locales/en/translation.json
Right now if Davi goes offline we get a white screen for multiple errors. Adding a wrapper around Router to display a "no internet connection" card. 
Closes https://github.com/DXgovernance/DAVI/issues/416
=> Offline screen

src/hooks/Guilds/contracts/useRichContractRegistry.ts
On development use richcontracts from src/configs/ and on production uses "contracts.projectdavi.eth"
creating a proposal i checked that external contracts where the ones on src/configs
=> use local richContract on development

richContracts.json, src/configs/index.ts, src/utils/bytes.ts
Add extra validation for bytes 32 as talked with @rossneilson 
=> add extra validation for bytes32

src/provider/chains.ts
=> fix: Overrides default rpc to pokt for mainnet

package.json
=> docs: Increment version to 2.1.1

package.json
Increased version number to 2.2.0
=> Deploy: Increased version number to 2.2.0

src/Modules/Guilds/Hooks/useTimeDetail.ts, src/components/primitives/Forms/AddressInput/AddressInput.tsx
Also added a validation of null on useTimeDetail.ts
Closes #448 
- Create a proposal
- Add action
- Transfer
- On Recipient try to add white spaces and it shouldn't allow you
=> Fix: white spaces on address input

src/components/Header/Header.tsx, src/components/Web3Modals/NetworkModal/NetworkModal.tsx, src/components/Web3Modals/WalletModal/WalletModal.tsx, src/provider/ReadOnlyConnector.ts
Closes #447 
open the app without specifying a chain
=> Fixing white screen when url had no network

src/components/ActionsBuilder/SupportedActions/SetPermissions/SetPermissionsEditor.tsx, src/components/ActionsBuilder/SupportedActions/SetPermissions/validateSetPermissions.ts, src/components/primitives/Forms/NumericalInput.tsx
Allow setting of value in function call permissions setting
[Screencast from 09-12-22 12:01:47.webm](https://user-images.githubusercontent.com/5303411/206737804-c3f29888-3576-46a5-aebe-d958bcd20a89.webm)
Closes #442 
Create proposal, add action, set permissions, function call, change amount
=> Allow setting of value in function call permissions setting

.github/workflows/preview-deploy.yml
=> feat: Adding new gateway to ipfs preview

src/bytecodes/prod.json, src/configs/mainnet/config.json, src/configs/xdai/config.json
=> feat: Adding new bytecode for rep guilds and registry in mainnet and gc

src/Modules/Guilds/Hooks/useDiscussionContext.ts, src/Modules/Guilds/pages/Discussion/Discussion.tsx, src/Modules/Guilds/pages/Proposal/Proposal.tsx
=> Better context naming for orbis

src/Modules/Guilds/Hooks/useDiscussionContext.ts, src/Modules/Guilds/pages/Discussion/Discussion.tsx, src/Modules/Guilds/pages/Proposal/Proposal.tsx
=> fix: Removing test from orbis context
