DXgovernance/DAVI

src/Components/Fixtures/index.ts
src/Modules/Guilds/Wrappers/SidebarInfoCardWrapper.tsx
src/hooks/Guilds/ether-swr/guild/useGuildConfig.ts
src/hooks/Guilds/ether-swr/guild/useSnapshotId.ts
src/hooks/Guilds/ether-swr/guild/useVotingResults.ts
src/hooks/Guilds/useVoteSummary.ts
src/old-components/Guilds/ProposalPage/ProposalInfoCard/index.tsx
src/old-components/Guilds/Sidebar/MemberActions.tsx
src/old-components/Guilds/StakeTokensModal/StakeTokens.tsx
src/pages/Guilds/Proposal.tsx

TotalLocked was being pulled from guildconfig hook. That hook wasn't considering snapshot based implementations so totalLocked was returning null and voting info was empty. 
Solution: 
- remove totalLocked key from useGuildConfig hook. 
- Refactor all components that were using totalLocked key from guildConfig. 
- Implement useTotalLocked in those cases and also get the snapshotId at the proposal level where is possible. 
- In useVoteSummary hook I removed the 1st entry in proposal.totalVotes and not the last as it was, since votes weren't being shown. 
Closes https://github.com/DXgovernance/DAVI/issues/48
Before:
After:

Fix repguild

---

src/Components/ProposalCard/ProposalCard.styled.ts
src/Components/ProposalCard/ProposalCard.tsx
src/Components/ProposalCard/__snapshots__/ProposalCard.test.tsx.snap
src/Modules/Guilds/Wrappers/ProposalCardWrapper.tsx

On guild page we show a list of ProposalCardWrappers with no proposal id (just to show some loading proposals). 
If we clicked there we where redirecting to invalid url. 
The fix is to avoid that is no proposalId prop is passed, we shouldn't be able to click on proposal. 
Closes https://github.com/DXgovernance/DAVI/issues/54

Avoid redirect when skeleton (loading) proposalCard is displayed

---

src/Components/ActionsBuilder/SupportedActions/ERC20Transfer/ERC20TransferEditor.tsx
src/Components/ActionsBuilder/SupportedActions/SetPermissions/SetPermissionsEditor.tsx

These token pickers are always wanting to show the DAO's holdings in this case so we can just pass the guild ID as in permission registry's picker we see the user's holdings

fix: Specify guild id for token picker

---

src/index.tsx

The global error boundary was a bit trigger happy and was getting triggered unnecessarily. The Global error boundary was initially added to show a warning on DXvote when the cache loading fails and no longer is relevant. I think we should implement localized error boundaries at some point instead of having a global one.
On a separate issue, the app seems to try to connect to localhost RPCs somewhere in our code and fails with an unhandled exception, which I believe in turn triggered the error boundary. This should be investigated later and might even be solved after the recent refactors.
Tested on preview deployments.

fix: Remove global error boundary.

---

src/bytecodes/local.json
src/components/ActionsBuilder/CallDetails/CallDetails.styled.tsx
src/components/ActionsBuilder/CallDetails/CallDetails.tsx
src/components/ActionsBuilder/CallDetails/__snapshots__/CallDetails.test.tsx.snap
src/components/ActionsBuilder/SupportedActions/GenericCall/GenericCallParamsMatcher.tsx
src/components/ActionsBuilder/SupportedActions/GenericCall/__snapshots__/GenericCallInfoLine.test.tsx.snap
src/components/ActionsBuilder/SupportedActions/GenericCall/__snapshots__/GenericCallParamsMatcher.test.tsx.snap
src/components/ActionsBuilder/SupportedActions/index.tsx
src/components/Avatar/ENSAvatar.tsx
src/locales/en/translation.json
src/utils/index.ts
src/utils/strings.test.ts
src/utils/strings.ts

Show the parameters in a simple way once initially expanding generic call actions.
Closes https://github.com/DXgovernance/DAVI/issues/207
https://user-images.githubusercontent.com/25844967/189235418-7bd61481-8750-4526-a545-70eea998073a.mov

Display consistent params for generic calls

---

src/Modules/Social/Discussions.tsx

When removed `useRef` didn't delete the `current` property from the `orbis` object, causing an error while fetching discussions.
Manual testing

hotfix: fetch discussions

---

src/Modules/Guilds/Wrappers/ProposalCardWrapper.tsx
src/Modules/Guilds/pages/AllProposals/AllProposals.tsx
src/Modules/Guilds/pages/Governance/Governance.tsx
src/Modules/Guilds/pages/Proposal/Proposal.tsx
src/components/ProposalCard/ProposalCard.tsx
src/components/ProposalCard/ProposalCardWinningOption/ProposalCardWinningOption.test.tsx
src/components/ProposalCard/ProposalCardWinningOption/ProposalCardWinningOption.tsx
src/components/ProposalCard/ProposalCardWinningOption/types.ts
src/components/ProposalCard/__snapshots__/ProposalCard.test.tsx.snap
src/hooks/Guilds/erc20/useERC20Info.test.ts
src/hooks/Guilds/erc20/useERC20Info.ts

- Display wining option if any. By default show option index 0. Previously we were ordering options at card wrapper level. Since choosing wining option seems to be concern from `ProposalCardWinningOption` I refactored it so it handles that logic.
- While I was testing I found 2 issues/warnings: 
1. useERC20Info hook braking the app because of this line ` totalSupply: BigNumber.from(data[3]),` where data[3] was null. 
2. missing translation key (wrong path to key)
Closes https://github.com/DXgovernance/DAVI/issues/277

Display winning option

---

src/Modules/Guilds/Hooks/useProposal.ts
src/Modules/Guilds/Hooks/useTotalLocked.ts
src/Modules/Guilds/Hooks/useVotingPowerOf.ts
src/components/StakeTokensModal/components/StakeTokensForm/StakeTokensForm.styled.ts

We were getting current snapshot id in a lot of places and using that to get total locked and voting power of. However if we are not looking at a proposal directly we do not want to do this as a new current snapshot id is only ever created once a proposal is made. So we cannot rely on this to get the most up to date token locked state. This resulted in users not being able to lock tokens or join the guild, now fixes. 
Closes #316

Hotfix: Fixing total locked in snapshot guild

---

src/Modules/Guilds/Hooks/useIsProposalCreationAllowed.tsx

Fixes the app crashing with a white screen due to Ethers getting a null value.

fix: Crash due to ethers receiving null value.

---

.github/workflows/codeql-analysis.yml

This PR implements GitHub's CodeQL code scanning for DAVI. The configuration is unchanged from the defaults GitHub provide, which seems to work fine.
Currently it finds and flags our hardcoded Pinata key as a critical vulnerability (which makes sense), but that can be ignored for now.
Tested in my fork, as seen [here](https://github.com/mprasanjith/DAVI/pull/11).

Add CodeQL scanning workflow.

---

.github/workflows/integration-tests.yml
cypress/config/development.json
scripts/integration.sh

This pr contains added cypress dashboard for synpress tests. It will only use the Dashboard on merging to the develop and when the pr contains either ready-for-tests or QA label.
Right now we got a litlle problem with test capacity in cypress dashboard, but as soon as the sorry-cypress will be implemented in synpress we will switch to them and use bunch of stuff like parallelisation etc.

Added cypress dashboard for integration tests

---

src/components/ProposalStatus/ProposalStatus.tsx

The proposal status pill has different colors depending on the status.
A change I made from the discussion is that "Executed" proposals are grey instead of a shade of green. I think this de-emphasizes them as they're already past proposals.
Currently I think there's no way to trigger a "Finished" state, but it is still configured to show a grey pill (the same as "Executed")
Closes #334 
Manual testing.

Feat: Proposal status pill is colored depending on status

---

src/Modules/Guilds/pages/AllProposals/AllProposals.styled.tsx
src/Modules/Guilds/pages/Governance/Governance.tsx

Hide "Discussions" features behind flag:
1. "Create Discussion" button at the top of the page
2. "Discussions" section in the "Governance" page
Discussions should be visible anywhere but in the production environment.
Also fixed a vertical scrollbar in "All proposals" page.

Fix: hide discussions

---

src/components/ActionsModal/components/ParamsForm/FormElementRenderer.tsx
src/components/primitives/Forms/IntegerInput/IntegerInput.stories.tsx
src/components/primitives/Forms/IntegerInput/IntegerInput.test.tsx
src/components/primitives/Forms/IntegerInput/IntegerInput.tsx
src/components/primitives/Forms/IntegerInput/index.ts

Added a new component: `<IntegerInput>` that takes the implementation of `<NumericalInput>` but prevents the user from inputting dots.
An alternative would've been to add a prop to `NumericalInput`, but `FormElementRenderer` doesn't accept components with props.
Closes #410 
1. Go to the proposal creation page
2. Add a new action: "Swapr fee"
3. The component to input the fee is an `IntegerInput`
4. It shouldn't let a user input anything but numbers

Fix: component breaks after decimal value

---

src/components/StakeTokensModal/components/StakeTokensForm/__snapshots__/StakeTokensForm.test.tsx.snap
src/components/primitives/Forms/TokenAmountInput.tsx

Fixed auto-formatting issue in the `TokenAmountInput` component.
Before: after a delay of 350ms the field will auto-format, adding a dot and a decimal.
Now: it doesn't format it automatically. If the value is invalid (like ending with a dot) it will change the value to `null` and prevent the form from submitting.
1. Go to the new proposal page, and select a new "Transfer" action
2. The "Amount" input shouldn't auto-format, nor let you submit if the number ends with a dot.

Fix: TokenAmountInput auto-formatting issue

---

package.json
yarn.lock

Use commit hash instead of branch name as pkg dependency.

Dxdao-contracts pkg

---

src/components/ActionsBuilder/SupportedActions/SetGuildConfig/SetGuildConfigEditor.tsx
src/components/ActionsBuilder/SupportedActions/SetGuildConfig/__snapshots__/SetGuildConfigEditor.test.tsx.snap
src/components/ActionsBuilder/SupportedActions/SetGuildConfig/validateSetGuildConfig.ts
src/components/primitives/Forms/DurationInput/DurationInput.tsx
src/components/primitives/Forms/Input/Input.tsx
src/components/primitives/Forms/NumericalInput.tsx
src/locales/en/translation.json

- Add conditional flag to display (or not) X icon on `NumericalInput` component to avoid founded issue.
- Display proper error label on `lockTime` and `proposalTime` fields for setGuildConfig Actions. Only display error for updated field, not both.
Closes https://github.com/DXgovernance/DAVI/issues/427

Locktime & proposalTime error label fix

---

src/components/ProposalDescription/ProposalDescription.styled.tsx
src/components/ProposalDescription/__snapshots__/ProposalDescription.test.tsx.snap

Long words with no spacing (like long links) in the proposal description were not contained and overlapped with other elements. Also, spacing between words was uneven.
Now it breaks words in multiple lines, and aligns text to the left instead of justified.
Proposal referenced in the issue:
Long proposal description with long link (ft. ChatGPT):
Closes #438 
Snapshot test.

Fix: proposal text not contained

---

scripts/dev.sh

This changes the hostname of the local hardhat node to 0.0.0.0. This will run the node on all network interfaces, including the one Docker uses. Without this, DAVI Subgraph running on Docker can't access the local hardhat node.

fix: Changes to support subgraph in docker.

---

src/Modules/Guilds/Hooks/useETHPermissions.test.ts
src/Modules/Guilds/Hooks/useETHPermissions.ts
src/components/ActionsBuilder/Action/Action.tsx
src/components/ActionsBuilder/Option/Option.tsx
src/components/ActionsBuilder/utils.ts
src/hooks/Guilds/contracts/useDecodedCall.ts

Closes: 
- DXgovernance/davi-monorepo#5 
- DXgovernance/davi-monorepo#4
- DXgovernance/davi-monorepo#3
- Removing call from editable action and checking null.
- Iterating on decodedActions instead of Actions for options
- Fix on getPermissionArgs for raw transactions
both bugs found with madusha and ross
Before: 
[Screencast from 15-12-22 12:05:41.webm](https://user-images.githubusercontent.com/5303411/207896117-50db9eac-0937-496b-96f8-911d4bb14b21.webm)
After: 
[Screencast from 15-12-22 12:06:54.webm](https://user-images.githubusercontent.com/5303411/207896140-c68a72be-3e34-491d-953b-3953d5bbe796.webm)
adding action vesting contracts

Various fix on actions (Vestings and raws) 
